// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPb3uY6ad0T7suiBP5Sg-BwxXGV3S01EE',
    appId: '1:647079573672:web:bda78a129860c556926a9d',
    messagingSenderId: '647079573672',
    projectId: 'cl-project-31719',
    authDomain: 'cl-project-31719.firebaseapp.com',
    storageBucket: 'cl-project-31719.firebasestorage.app',
    measurementId: 'G-JEJPF6NYHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABWF3McM4GoGIynxKfOH1MTkhljThf7TQ',
    appId: '1:647079573672:android:2e72a1e564a963f6926a9d',
    messagingSenderId: '647079573672',
    projectId: 'cl-project-31719',
    storageBucket: 'cl-project-31719.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSkgW7dLesIiXpZyhNUFL90UBmZcSsdXQ',
    appId: '1:647079573672:ios:79347f8eab71181a926a9d',
    messagingSenderId: '647079573672',
    projectId: 'cl-project-31719',
    storageBucket: 'cl-project-31719.firebasestorage.app',
    iosBundleId: 'com.example.clFashion',
  );

}